[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Temporarily commented out CSP to fix blank page issue
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-src 'self';"

# Redirect specific paths to index.html for SPA routing (excluding functions)
# Note: Functions are automatically excluded by Netlify

[[redirects]]
  from = "/upload-cv"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/upload-job-description"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/analyze-now"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/account"
  to = "/index.html"
  status = 200

# Catch-all redirect for SPA routing (excludes functions)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
